In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("Pokemon.csv")
data.head(n=10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

# Assignment 2: Add two colums High_low_speed and High_low_HP in the same dataset as we worked in class.
Dataset Link: http://www.kaggle.com/abcsds/pokemon.

# Feature Engineering
Add Coulum

In [29]:
data["Attack"].mean()

79.00125

In [26]:
#attach above 79 = is called high attack
#attach below 79 = is called low attach

In [6]:
def set_attack(val):
    if val < attack_mean:
        return "Attack Low"
    elif val == attack_mean:
        return "Attack neutral"
    else:
        return "Attack High"

In [7]:
# "Attack_high_low"  -> "Attack High" , "Attack Low"
data["Attack_high_low"] = data["Attack"].apply(set_attack)
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Attack_high_low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Attack Low
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Attack Low
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Attack High
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Attack High
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Attack Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Attack High
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Attack High
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Attack High
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Attack High
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Attack High

In [25]:
data.groupby("Type 1").groups

{'Bug': [13, 14, 15, 16, 17, 18, 19, 51, 52, 53, 54, 132, 136, 137, 179, 180, 181, 182, 208, 219, 220, 228, 229, 230, 231, 232, 288, 289, 290, 291, 292, 307, 308, 314, 315, 316, 342, 343, 446, 447, 457, 458, 459, 460, 461, 462, 463, 520, 600, 601, 602, 603, 604, 605, 618, 619, 649, 650, 656, 657, 677, 678, 693, 697, 698, 717, 732, 733, 734], 'Dark': [212, 213, 233, 246, 247, 248, 284, 285, 326, 327, 392, 393, 478, 512, 549, 568, 569, 620, 621, 631, 632, 685, 686, 690, 691, 694, 695, 696, 756, 757, 793], 'Dragon': [159, 160, 161, 365, 366, 406, 407, 408, 409, 417, 418, 419, 420, 425, 426, 491, 492, 493, 494, 671, 672, 673, 682, 706, 707, 710, 711, 712, 774, 775, 776, 794], 'Electric': [30, 31, 88, 89, 108, 109, 134, 146, 157, 186, 193, 194, 195, 196, 258, 262, 337, 338, 339, 340, 341, 448, 449, 450, 464, 513, 517, 531, 532, 533, 534, 535, 536, 581, 582, 648, 663, 664, 665, 704, 705, 764, 765, 772], 'Fairy': [40, 41, 187, 189, 190, 225, 226, 519, 737, 738, 739, 752, 753, 754, 755, 770, 792], 'Fighting': [61, 62, 72, 73, 74, 114, 115, 255, 256, 320, 321, 334, 335, 336, 496, 497, 498, 592, 593, 594, 598, 599, 680, 681, 742, 743, 771], 'Fire': [4, 5, 6, 7, 8, 42, 43, 63, 64, 83, 84, 135, 147, 158, 169, 170, 171, 236, 237, 259, 263, 270, 276, 277, 278, 279, 352, 353, 354, 355, 435, 436, 437, 518, 542, 557, 558, 559, 572, 573, 614, 615, 616, 692, 721, 722, 723, 730, 731, 735, 736, 799], 'Flying': [702, 703, 790, 791], 'Ghost': [99, 100, 101, 102, 215, 385, 386, 387, 388, 389, 472, 473, 477, 490, 529, 544, 545, 623, 624, 668, 669, 670, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787], 'Grass': [0, 1, 2, 3, 48, 49, 50, 75, 76, 77, 110, 111, 122, 166, 167, 168, 197, 202, 203, 204, 206, 207, 272, 273, 274, 275, 296, 297, 298, 309, 310, 344, 362, 363, 390, 432, 433, 434, 451, 452, 467, 468, 505, 509, 510, 511, 516, 521, 550, 551, 554, 555, 556, 570, 571, 606, 607, 608, 609, 617, 651, 652, 658, 659, 701, 718, 719, 720, 740, 741], 'Ground': [32, 33, 55, 56, 112, 113, 119, 120, 222, 250, 251, 359, 360, 361, 375, 376, 423, 424, 499, 500, 515, 523, 588, 589, 611, 612, 613, 679, 683, 684, 708, 709], 'Ice': [133, 156, 238, 239, 243, 257, 395, 396, 397, 398, 399, 400, 415, 522, 524, 530, 643, 644, 645, 674, 675, 676, 788, 789], 'Normal': [20, 21, 22, 23, 24, 25, 26, 27, 44, 45, 57, 58, 90, 91, 92, 116, 121, 123, 124, 138, 143, 144, 148, 155, 175, 176, 177, 178, 188, 205, 218, 221, 234, 235, 252, 253, 254, 260, 261, 286, 287, 299, 300, 311, 312, 313, 317, 318, 319, 322, 324, 325, 358, 364, 367, 383, 384, 441, 442, 443, 444, 445, 471, 474, 475, 476, 479, 480, 488, 489, 495, 514, 525, 543, 552, 563, 564, 565, 566, 567, 578, 579, 580, 590, 591, 633, 634, 646, 647, 687, 688, 689, 715, 716, 727, 728, 729, 744], 'Poison': [28, 29, 34, 35, 36, 37, 38, 39, 46, 47, 95, 96, 117, 118, 183, 345, 346, 368, 482, 483, 501, 502, 503, 504, 629, 630, 760, 761], 'Psychic': [68, 69, 70, 71, 104, 105, 131, 162, 163, 164, 165, 191, 192, 211, 216, 217, 269, 271, 303, 304, 305, 306, 356, 357, 391, 394, 428, 429, 430, 431, 481, 487, 526, 527, 537, 538, 539, 546, 553, 576, 577, 586, 587, 622, 635, 636, 637, 638, 639, 640, 666, 667, 745, 746, 747, 797, 798], 'Rock': [80, 81, 82, 103, 149, 150, 151, 152, 153, 154, 200, 265, 266, 267, 268, 323, 369, 370, 377, 378, 379, 380, 414, 453, 454, 455, 456, 486, 528, 583, 584, 585, 627, 628, 700, 758, 759, 766, 767, 768, 769, 773, 795, 796], 'Steel': [223, 224, 245, 328, 329, 330, 331, 332, 333, 410, 411, 412, 413, 416, 427, 484, 485, 540, 660, 661, 662, 699, 748, 749, 750, 751, 777], 'Water': [9, 10, 11, 12, 59, 60, 65, 66, 67, 78, 79, 85, 86, 87, 93, 94, 97, 98, 106, 107, 125, 126, 127, 128, 129, 130, 139, 140, 141, 142, 145, 172, 173, 174, 184, 185, 198, 199, 201, 209, 210, 214, 227, 240, 241, 242, 244, 249, 264, 280, 281, 282, 283, 293, 294, 295, 301, 302, 347, 348, 349, 350, 351, 371, 372, 373, 374, 381, 382, 401, 402, 403, 404, 405, 421, 422, 438, 439, 440, 465, 466, 469, 470, 506, 507, 508, 541, 547, 548, 560, 561, 562, 574, 575, 595, 596, 597, 610, 625, 626, ...]}

In [18]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Attack_high_low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Attack Low
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Attack Low
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Attack High
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Attack High
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Attack Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
366,334,AltariaMega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,3,False,Attack High
702,641,TornadusIncarnate Forme,Flying,NaN,580,79,115,70,125,80,111,5,True,Attack High
703,641,TornadusTherian Forme,Flying,NaN,580,79,100,80,110,90,121,5,True,Attack High
790,714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False,Attack Low
791,715,Noivern,Flying,Dragon,535,85,70,80,97,80,123,6,False,Attack Low